### ISSUE TITLE
Missing recommended Android proguard rules in documentation

### ISSUE THREAD

**Issue by ForestTree** [lime-company/powerauth-mobile-sdk#120]
Please add recommended proguard rules into PowerAuth SDK for Android documentation.
Are these rules enough for production builds?

> -keep class io.getlime.security.powerauth.** { *; }
> -keep class io.getlime.core.** { *; }

**Comment by TomasKypta** [comment]
I'll check it out.
But it seems that these rules are unnecessarily too strong - keeping everything and disallowing any obfuscation.

Also I guess that it's better to include PowerAuth SDK ProGuard configuration as consumerProguardFiles that is directly packaged into the aar. 
In this case the configuration has to be as defensive as possible (only rules necessary for the SDK to still work).
