### ISSUE TITLE
Detection of devicePublicKey

### ISSUE THREAD

**Issue by ludekvlk** [lime-company/powerauth-mobile-sdk#51]
We had an issue when we updated to new PA. There is detection of devicePublicKey in PrivateTypes.cpp:ValidatePersistentData().

Unfortunately previous PA 1.5 does not have stored devicePublicKey and a lot of people have already migrated without devicePublicKey. 

Solution for us is change `result = result && pd.serverPublicKey.size() > 0 && pd.devicePublicKey.size() > 0;` 

to 
` result = result && pd.serverPublicKey.size() > 0;`.

Any ideas how to fully migrate to newest versions?

**Comment by petrdvorak** [comment]
We have several migration options:

- We can relax validation on the public key, maybe as an optional feature.
- We can implement one-time derivation of the device public key from the private key in vault.
- We can re-activate clients using the new SDK, so that the public key is re-created.

**Comment by hvge** [comment]
Related to #6

I'll make that data validation less strict, but that will be just temporary change. We still need to decide whether the device public key will be used in the future and if yes, then I'll implement a better solution for this ticket.

**Comment by hvge** [comment]
Release 0.16.1 contains that relaxed validation

**Comment by hvge** [comment]
Release 0.17.0 will have a full internal support for old data format. I hope that this finally solve all your problems and you'll no longer need to maintain a forked version of SDK.
