### ISSUE TITLE
Determine how to store / retrieve "device public key" and why we need it

### ISSUE THREAD

**Issue by petrdvorak** [lime-company/powerauth-mobile-sdk#6]
Couple unsorted observations:

(1) The old PA2.0 SDK (used in MONETA) did not persist device public key in session state. Hence it is not possible to migrate this value from the old SDK version to the new one easily. As a result, the device public key should be optional in the session state, otherwise we won't be able to update.

(2) Device public key can be reconstructed when the device private key is known.

(3) We currently do not have any good use-case for the device public key. Theoretically, we could use it for:

- non-authenticated end-to-end encryption (to allow device encrypt data that are sent to the server)
- incoming data signature validation (server could sign data with a device private key)

However, these are more "possible technologies" than "something that we know why we need it"...

**Comment by hvge** [comment]
Already resolved in #51
