### ISSUE TITLE
Improve codebase so that base of PA2Client uses encryption type as an input

### ISSUE THREAD

**Issue by petrdvorak** [lime-company/powerauth-mobile-sdk#7]
Currently, we have one method that uses E2EE. The method handles the request/response object encryption itself, on a high-level interface (in `PowerAuthSDK` class). When we have more, methods that use E2EE, this will cause an issue. We should move E2EE support more deep, into `PA2Client` class (base method, with NSData transport).

**Comment by hvge** [comment]
Closing. This issue is no longer relevant. We're going to change basic E2EE principles in future protocol upgrades and that change will bring also a rework on networking classes.
