### ISSUE TITLE
Improve networking error handling on Android sdk

### ISSUE THREAD

**Issue by hcsmatti** [lime-company/powerauth-mobile-sdk#75]
Currently we have to parse manually Json object from response. Sdk could prepare the object for us.

**Comment by petrdvorak** [comment]
We should improve the error handling in similar manner as we did on iOS. Currently, we correctly return error response. However, the object only contains raw response body.

**Comment by hvge** [comment]
From now, both `FailedApiException` and `ErrorResponseApiException` may contain response body and `JsonObject`, parsed from that body.
