### ISSUE TITLE
Android: Password strength evaluation - "Strong" passwords reported as "Invalid"

### ISSUE THREAD

**Issue by petrfuka** [lime-company/powerauth-mobile-sdk#79]
Hello,
the Android SDK has an error in password strength evaluation for passwords of 6 digits or longer. They are reported as PasswordStrength.INVALID.

This condition is the culprit, at PasswordUtil:77
```
if (!PasswordUtil.isStrong(password, type)) {
    return PasswordStrength.STRONG;
}
```

The whole condition there is strange, though. If a password isn't invalid from checking isValid(), it probably shouldn't return PasswordStrength.INVALID but should return one of the actual strength values.
Something like: Check if it's not valid -> return INVALID, check if it's weak -> return WEAK, check if it's strong -> return STRONG, otherwise return NORMAL.

**Comment by petrdvorak** [comment]
IMO copy paste issue, the condition should not use `!`... @hvge please double-check...

**Comment by hvge** [comment]
The same issue is on IOS 🥇

**Comment by hvge** [comment]
...and you're right, that evaluation was weird.
